# runner.conf
root: ./cmd/api          # folder yang di-watch
tmp_path: ./cmd/api/tmp  # temporary folder untuk build
build_delay: 500     # ms
build_args: 
  - -o
  - ./cmd/api/bin/api.exe
run_args:
  - ./cmd/api/bin/api.exe