// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

type Permission struct {
	ID   int32
	Key  string
	Name string
}

type Role struct {
	ID   int32
	Name string
}

type RolePermission struct {
	RoleID       int32
	PermissionID int32
}

type User struct {
	ID       int32
	Name     string
	Password string
	Email    string
}

type UserRole struct {
	UserID int32
	RoleID int32
}
